require: 'rubocop-rspec'

inherit_gem:
  ryu39cop:
    - 'config/rubocop.yml'
    - 'config/rspec.yml'

AllCops:
  TargetRubyVersion: 2.3

RSpec/DescribeClass:
  Exclude:
    - 'integration_test/**/*_spec.rb'

RSpec/FilePath:
  Enabled: false
  Exclude:
    - 'spec/**/*_spec.rb'

