language: ruby

rvm:
  - ruby-head
  - 2.4.1
  - 2.3.4

sudo: false

script:
  - 'bundle exec rubocop'
  - 'bundle exec rspec'
  - 'bundle exec rspec integration_test/'
after_success:
  - 'bundle exec codeclimate-test-reporter'

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
